name: subscripify
description: "Stop unwanted charges. Track bills & subscriptions offline. No bank linking."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.19.0
  google_fonts: ^6.2.1

  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

  #ads
  google_mobile_ads: ^5.1.0

  #url_launcher
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generators
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

  # Icon Generator (Added this line)
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

# --- MOVED THIS SECTION OUTSIDE OF "flutter:" ---
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21